OPEN_MODULES=\
  all,\
  all-rx,\
  auth,\
  auth-rx,\
  common,\
  common-rx,\
  network,\
  network-rx,\
  share,\
  share-rx,\
  navi,\
  talk,\
  talk-rx,\
  template,\
  user,\
  user-rx,\
  friend,\
  friend-rx,\
  automotive,\
  cert
OPEN_SAMPLES=\
  sample,\
  sample-rx,\
  sample-common
